services:
  - type: web
    name: front-tienda
    env: static
    buildCommand: npm install && npm run build -- --configuration production
    staticPublishPath: ./dist/fornt_tienda/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
